### ISSUE TITLE
Favor excon instead of httpclient

### ISSUE THREAD

**Issue by lovehandle** [lovehandle/agent_cooper#3]
@hakanensari -- was bumping deps today, and i was actually considering deprecating httpclient in favor of excon when i noticed you had already forked the repo and began working on it.

would love to pull that back into master when you're done. made some refactors today to the code base that may make the merge a little messy, but feel free to send me a PR and i'll take care of the rest.

**Comment by hakanensari** [comment]
Of course, will send one giant pull request as I was not clinical, committing everything to master. :smile:

So far, in addition to swapping HTTPClient with Excon, I've gutted Nokogiri (let the programmer choose however they want to parse) and Virtus (It feels a bit limited value in this context. Also, not sure if it was a bug, but when I upgraded to v1.0, default values were not transferring over when the concrete requests inherited from the base class.).

BTW, just curious, but does this project have any relevance in your current work?

Finally, off topic, but you had an unscrubbed API key in some cassettes. I didn't take the time to check, but in the remote case that key should be private, I'd suggest you revoke and reissue.

**Comment by lovehandle** [comment]
Cheers. Thanks so much for the work! This repo has been in dire need of a makeover for quite some time now.

RE: relevance to my current work -- Only a hobby at the moment. I created this for a book price comparison engine I wrote a few years ago (was actually using it in conjunction with your Sucker gem from way back when). Hoping to pick it up again at some point.

Love what you guys do at papercavalier, btw.

**Comment by hakanensari** [comment]
Thanks. In fact, I retired (from) that. I'm currently working on a couple of things, including [this](http://part.ly). Hence my renewed interest in eBay :smile: 

> Love what you guys do at papercavalier, btw.

**Comment by lovehandle** [comment]
Ah, yeah -- I saw that earlier. Have you heard about [Kimonify](https://www.kimonolabs.com/)? I think if I were to do it again, I'd use something like that for managing the horde of book vendors that don't actually have established API's.

(PS: treating GH Issues like email = great success ftw)
